### ISSUE TITLE
Phoenix Digital inputs 7-9 are not supported

### ISSUE THREAD

**Issue by jvetter1** [BrewTroller/BrewTroller-Official#32]
The phoenix adds three additional digital inputs that are not supported. the pinInit needs to be updated to add support for these three extra inputs.

Note that the third extra input is the e-stop input.

**Comment by jvetter1** [comment]
Reference commits:
- https://github.com/brewtrollergit/brewtroller/commit/da4353ce1197bbc7398f9095dafc04bb5f5f70fa
- https://github.com/brewtrollergit/brewtroller/commit/560d08f334491c16dcbeecf6292bb5d70380b54d

**Comment by mrshake** [comment]
I would set this as a high priority bug fix
