### ISSUE TITLE
Compilation fails when RGBIO is enabled

### ISSUE THREAD

**Issue by jvetter1** [BrewTroller/BrewTroller-Official#34]
When the RGBIO boards are enabled in the config.h the compilation of the .hex will fail. 

This is mostly due to an organization problems between the .cpp and .h

**Comment by jvetter1** [comment]
Reference commits from other repo:
- https://github.com/brewtrollergit/brewtroller/commit/00a9d1b688fa679d0fef8a57b793a9b6fed04545
- https://github.com/brewtrollergit/brewtroller/commit/1115e58e4e25e3e4238bbf858d7d5e8e12983e02

**Comment by mrshake** [comment]
This one needs to be a high priority.  We have users who this will directly affect
